nome = input("Qual seu nome? ")
apelido = input("Qual seu apelido? ")
endereco = input("Qual seu endereco? ")
cidade_cep = input("Qual cidade e cep? ")
print(f"{nome} {apelido} - {endereco} - {cidade_cep}")